name: CD - Deploy to AWS ECS Fargate

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: sa-east-1
      PROJECT_NAME: jwt-validator
      ECR_REPOSITORY: jwt-validator-repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::442956083887:role/GitHubActionsDeployRole
          role-session-name: deploy-session

      # Login ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Install OpenTofu
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.7.0

      # Create ONLY the ECR repository first
      - name: Create ECR before pushing image
        working-directory: infrastructure
        run: tofu apply -target=aws_ecr_repository.jwt_validator -auto-approve

      # Docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag "$IMAGE" \
            --push \
            .

          echo "IMAGE_URL=$IMAGE" >> $GITHUB_ENV

      # Write dynamic image into Terraform variables
      - name: Write image URL to TF vars
        run: |
          echo "image_url=\"${IMAGE_URL}\"" > infrastructure/auto.tfvars

      # Terraform init + plan + apply
      - name: Terraform Init
        working-directory: infrastructure
        run: tofu init

      - name: Terraform Plan
        working-directory: infrastructure
        run: tofu plan -out=tfplan

      - name: Terraform Apply
        working-directory: infrastructure
        run: tofu apply -auto-approve tfplan